INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)VALUES(10001, 'TEST','GET AWS Certified',CURRENT_DATE , false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)VALUES(10002, 'TEST','Learn Oracle DB',CURRENT_DATE , false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)VALUES(10003, 'TEST','Learn Oracle Cloud',CURRENT_DATE , false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)VALUES(10004, 'TEST','Learn Web Development',CURRENT_DATE , false);